# Generated by Django 2.2.6 on 2019-10-19 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Discente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('numero', models.CharField(max_length=12)),
                ('ano', models.IntegerField()),
                ('curso', models.CharField(max_length=50)),
            ],
        ),
    ]
